semgrep-scan:
  name: Semgrep Scans
  runs-on: ubuntu-latest
  container:
    # A Docker image with Semgrep installed. Do not change this.
    image: semgrep/semgrep@sha256:207983631beecdbe7fa29196c7f4a7a5f29033933cdb76c687ce4a672e07618d # 1.164.0
  permissions:
    # required for all workflows
    security-events: write
    # only required for workflows in private repositories
    actions: read
    contents: read

  steps:

    - name: Checkout Sources
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
        fetch-depth: 1

    - name: Run Semgrep using selected rules (metrics off)
      run: |
        semgrep scan --sarif --config auto . --output /tmp/semgrep-results.sarif || true

    - name: Upload Semgrep SARIF Results
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with: # Yep, you can open this file in your IDE: Just drag and drop it into IntelliJ IDEA or Visual Studio Code
        name: semgrep-scan-results.sarif
        path: /tmp/semgrep-results.sarif